# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa9a91041afdbaff23dde540c8640c79f1281580bd76f8f76370fcaf46ca5e02c740d634b1f523d454cb3ebc2d9078963f8938893327e3611fade0c3ae598458

test:
  secret_key_base: 0625b29c2438355a4b2b661b71d7a08640519f886dba24e49ba72de6f7311b55f419986d92937bce7312d8ce2cce9ff5e60417fab80649dfefa7f5c0b23ac83a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
